@baseUrl = http://localhost:3000

###
GET {{baseUrl}}/post

###
GET {{baseUrl}}/post/{POST_ID}

###
POST {{baseUrl}}/post
Content-Type: application/json

{
  "title": "Artigo #001",
  "contents": "Lorem ipsum dor",
  "userId": {USER_ID}
}

###
PATCH {{baseUrl}}/users/{USER_ID}
Content-Type: application/json

{
  "displayName": "Darlley Brito"
}

###
DELETE {{baseUrl}}/users/{USER_ID}
Content-Type: application/json