@baseUrl = http://localhost:3000

###
GET {{baseUrl}}/users

###
GET {{baseUrl}}/users/{USER_ID}

###
POST {{baseUrl}}/users
Content-Type: application/json

{
  "username": "naruto",
  "displayName": "Naruto Uzumaki",
  "avatarUrl": "https://github.com/darlley.png"
}

###
PATCH {{baseUrl}}/users/{USER_ID}
Content-Type: application/json

{
  "displayName": "Darlley Brito"
}

###
DELETE {{baseUrl}}/users/{USER_ID}
Content-Type: application/json