@baseUrl = http://localhost:3000

###
GET {{baseUrl}}/users

###
POST {{baseUrl}}/users
Content-Type: application/json

{
  "username": "Naruto",
  "displayName": "Darlley Brito",
  "avatarUrl": "https://github.com/darlley.png"
}